services:
  postgres:
    container_name: postgres-sql-shaikh
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456789
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: webStore_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5431:5432"
    networks:
      - postgres-net

networks:
  postgres-net:
    driver: bridge

volumes:
  postgres:
  pgadmin-data: