application:
  name: webStore
  security:
    jwt:
      secret-key: ${JWT_SECRET:1278f0e1ad725cf494ca5abab8d4efbcffa75837b5d4314567cb3d29862925f7c5b6606d417a2f2d6348ba7dd0038b9b5d58ea2cf32d1b28290abdf417356adcfa416703a25838a89460c6c6548041e7c99495e73c6db35ba5b114bb22effbb87424a168221d6f44293c81d39c8ba870cd1508348813ecc37df511747fe2986a00d86ee8c1ca0538f7f2623c031054d404bd3ee76b448768a75f0bc5221fc45556a885182ce8fc26e2f0b7e9283a5cd00620054d731d933ffb8eb033693122e620c01ef70eddcfcd86bc5aed260620c16813b6a7345228afd6d5bd9a2732586cfde2f780d5a0c2a03344457a4a81e6f381b8329edf2a7e009db20cb2a3ae55f6b1ccf3023462dc67dcc0d8d4f965a02e993f864f8e569062bbf1961b5147306ae48b4231e2c875d77be13cba2fb3ce0b111787f3cf084ac6e716fac62250001eb2e582262ee628ec7806fdf6da59da40e2a48389695083ef707a927c01e28bad674557fb11757aebdcd153219e3d7f30b3c67d677f4c2bcdedc769e146d915b3}
      expiration: ${JWT_EXPIRATION:31536000000}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000}

frontend:
  url1: ${FRONT_URL1:http://localhost:5173}
  url2: ${FRONT_URL2:http://localhost:5174}

upload:
  dir: ${UPLOAD_DIR:uploads}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5431/webStore_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456789}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  web:
    cors:
      allowed-origins:
        - ${FRONT_URL1:http://localhost:5173}
        - ${FRONT_URL2:http://localhost:5174}
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
server:
  port: ${SERVER_PORT:8082}

  servlet:
    context-path: /api/webStore
